<a href="https://colab.research.google.com/github/teamgaon/recommendation_algorithms_know/blob/main/220106_sji_lgbm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [101]:
!git clone --recursive https://github.com/Microsoft/LightGBM

Cloning into 'LightGBM'...
remote: Enumerating objects: 24675, done.
remote: Counting objects: 100% (314/314), done.
remote: Compressing objects: 100% (214/214), done.
remote: Total 24675 (delta 184), reused 155 (delta 99), pack-reused 24361
Receiving objects: 100% (24675/24675), 18.43 MiB | 11.26 MiB/s, done.
Resolving deltas: 100% (18158/18158), done.
Submodule 'include/boost/compute' (https://github.com/boostorg/compute) registered for path 'external_libs/compute'
Submodule 'eigen' (https://gitlab.com/libeigen/eigen.git) registered for path 'external_libs/eigen'
Submodule 'external_libs/fast_double_parser' (https://github.com/lemire/fast_double_parser.git) registered for path 'external_libs/fast_double_parser'
Submodule 'external_libs/fmt' (https://github.com/fmtlib/fmt.git) registered for path 'external_libs/fmt'
Cloning into '/content/LightGBM/python-package/LightGBM/external_libs/compute'...
remote: Enumerating objects: 21733, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 21733 (delta 1), reused 2 (delta 0), pack-reused 21728
Receiving objects: 100% (21733/21733), 8.51 MiB | 11.84 MiB/s, done.
Resolving deltas: 100% (17567/17567), done.
Cloning into '/content/LightGBM/python-package/LightGBM/external_libs/eigen'...
remote: Enumerating objects: 113960, done.
remote: Counting objects: 100% (1171/1171), done.
remote: Compressing objects: 100% (553/553), done.
remote: Total 113960 (delta 707), reused 1061 (delta 618), pack-reused 112789
Receiving objects: 100% (113960/113960), 102.79 MiB | 19.17 MiB/s, done.
Resolving deltas: 100% (93564/93564), done.
Cloning into '/content/LightGBM/python-package/LightGBM/external_libs/fast_double_parser'...
remote: Enumerating objects: 692, done.
remote: Counting objects: 100% (192/192), done.
remote: Compressing objects: 100% (124/124), done.
remote: Total 692 (delta 95), reused 99 (delta 41), pack-reused 500
Receiving objects: 100% (692/692), 802.86 KiB | 4.67 MiB/s, done.
Resolving deltas: 100% (349/349), done.
Cloning into '/content/LightGBM/python-package/LightGBM/external_libs/fmt'...
remote: Enumerating objects: 28301, done.
remote: Counting objects: 100% (28301/28301), done.
remote: Compressing objects: 100% (7180/7180), done.
remote: Total 28301 (delta 19174), reused 28208 (delta 19125), pack-reused 0
Receiving objects: 100% (28301/28301), 13.47 MiB | 10.30 MiB/s, done.
Resolving deltas: 100% (19174/19174), done.
Submodule path 'external_libs/compute': checked out '36c89134d4013b2e5e45bc55656a18bd6141995a'
Submodule path 'external_libs/eigen': checked out '8ba1b0f41a7950dc3e1d4ed75859e36c73311235'
Submodule path 'external_libs/fast_double_parser': checked out 'ace60646c02dc54c57f19d644e49a61e7e7758ec'
Submodule 'benchmark/dependencies/abseil-cpp' (https://github.com/abseil/abseil-cpp.git) registered for path 'external_libs/fast_double_parser/benchmarks/dependencies/abseil-cpp'
Submodule 'benchmark/dependencies/double-conversion' (https://github.com/google/double-conversion.git) registered for path 'external_libs/fast_double_parser/benchmarks/dependencies/double-conversion'
Cloning into '/content/LightGBM/python-package/LightGBM/external_libs/fast_double_parser/benchmarks/dependencies/abseil-cpp'...
remote: Enumerating objects: 15927, done.
remote: Counting objects: 100% (53/53), done.
remote: Compressing objects: 100% (46/46), done.
remote: Total 15927 (delta 14), reused 19 (delta 7), pack-reused 15874
Receiving objects: 100% (15927/15927), 10.05 MiB | 15.15 MiB/s, done.
Resolving deltas: 100% (12294/12294), done.
Cloning into '/content/LightGBM/python-package/LightGBM/external_libs/fast_double_parser/benchmarks/dependencies/double-conversion'...
remote: Enumerating objects: 1267, done.
remote: Counting objects: 100% (111/111), done.
remote: Compressing objects: 100% (85/85), done.
remote: Total 1267 (delta 62), reused 49 (delta 24), pack-reused 1156
Receiving objects: 100% (1267/1267), 7.10 MiB | 10.23 MiB/s, done.
Resolving deltas: 100% (834/834), done.
Submodule path 'external_libs/fast_double_parser/benchmarks/dependencies/abseil-cpp': checked out 'd936052d32a5b7ca08b0199a6724724aea432309'
Submodule path 'external_libs/fast_double_parser/benchmarks/dependencies/double-conversion': checked out 'f4cb2384efa55dee0e6652f8674b05763441ab09'
Submodule path 'external_libs/fmt': checked out 'cc09f1a6798c085c325569ef466bcdcffdc266d4'

In [102]:
%cd /content/LightGBM

/content/LightGBM

In [103]:
!mkdir build
!cmake -DUSE_GPU=1
!make -j$(nproc)
!sudo apt-get -y install python-pip
!sudo -H pip install setuptools pandas numpy scipy scikit-learn -U
%cd /content/LightGBM/python-package/
!sudo python setup.py install --precompile

mkdir: cannot create directory ‘build’: File exists
-- Found OpenMP_C: -fopenmp
-- Found OpenMP_CXX: -fopenmp
-- Found OpenMP: TRUE
-- OpenCL include directory: /usr/include
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   filesystem
--   system
-- Using _mm_prefetch
-- Using _mm_malloc
-- Configuring done
-- Generating done
-- Build files have been written to: /content/LightGBM
[  2%] Built target lightgbm_capi_objs
[ 89%] Built target lightgbm_objs
[ 97%] Built target lightgbm
[100%] Built target _lightgbm
Reading package lists... Done
Building dependency tree
Reading state information... Done
python-pip is already the newest version (9.0.1-2.3~ubuntu1.18.04.5).
0 upgraded, 0 newly installed, 0 to remove and 37 not upgraded.
Requirement already satisfied: setuptools in /usr/local/lib/python3.7/dist-packages (60.2.0)
Requirement already satisfied: pandas in /root/.local/lib/python3.7/site-packages (1.3.5)
Requirement already satisfied: numpy in /root/.local/lib/python3.7/site-packages (1.21.5)
Requirement already satisfied: scipy in /usr/local/lib/python3.7/dist-packages (1.7.3)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.7/dist-packages (1.0.2)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (2018.9)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas) (1.15.0)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.7/dist-packages (from scikit-learn) (1.1.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn) (3.0.0)
/content/LightGBM/python-package
running install
/usr/local/lib/python3.7/dist-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  setuptools.SetuptoolsDeprecationWarning,
running build
running build_py
running egg_info
no previously-included directories found matching 'build'
warning: no files found matching 'LICENSE'
warning: no files found matching '*.txt'
warning: no files found matching '*.so' under directory 'lightgbm'
warning: no files found matching 'compile/CMakeLists.txt'
warning: no files found matching 'compile/cmake/IntegratedOpenCL.cmake'
warning: no files found matching '*.so' under directory 'compile'
warning: no files found matching '*.dll' under directory 'compile/Release'
warning: no files found matching 'compile/external_libs/compute/CMakeLists.txt'
warning: no files found matching '*' under directory 'compile/external_libs/compute/cmake'
warning: no files found matching '*' under directory 'compile/external_libs/compute/include'
warning: no files found matching '*' under directory 'compile/external_libs/compute/meta'
warning: no files found matching 'compile/external_libs/eigen/CMakeLists.txt'
warning: no files found matching 'compile/external_libs/eigen/Eigen/Cholesky'
warning: no files found matching 'compile/external_libs/eigen/Eigen/Core'
warning: no files found matching 'compile/external_libs/eigen/Eigen/Dense'
warning: no files found matching 'compile/external_libs/eigen/Eigen/Eigenvalues'
warning: no files found matching 'compile/external_libs/eigen/Eigen/Geometry'
warning: no files found matching 'compile/external_libs/eigen/Eigen/Householder'
warning: no files found matching 'compile/external_libs/eigen/Eigen/Jacobi'
warning: no files found matching 'compile/external_libs/eigen/Eigen/LU'
warning: no files found matching 'compile/external_libs/eigen/Eigen/QR'
warning: no files found matching 'compile/external_libs/eigen/Eigen/SVD'
warning: no files found matching '*' under directory 'compile/external_libs/eigen/Eigen/src/Cholesky'
warning: no files found matching '*' under directory 'compile/external_libs/eigen/Eigen/src/Core'
warning: no files found matching '*' under directory 'compile/external_libs/eigen/Eigen/src/Eigenvalues'
warning: no files found matching '*' under directory 'compile/external_libs/eigen/Eigen/src/Geometry'
warning: no files found matching '*' under directory 'compile/external_libs/eigen/Eigen/src/Householder'
warning: no files found matching '*' under directory 'compile/external_libs/eigen/Eigen/src/Jacobi'
warning: no files found matching '*' under directory 'compile/external_libs/eigen/Eigen/src/LU'
warning: no files found matching '*' under directory 'compile/external_libs/eigen/Eigen/src/misc'
warning: no files found matching '*' under directory 'compile/external_libs/eigen/Eigen/src/plugins'
warning: no files found matching '*' under directory 'compile/external_libs/eigen/Eigen/src/QR'
warning: no files found matching '*' under directory 'compile/external_libs/eigen/Eigen/src/SVD'
warning: no files found matching 'compile/external_libs/fast_double_parser/CMakeLists.txt'
warning: no files found matching 'compile/external_libs/fast_double_parser/LICENSE'
warning: no files found matching 'compile/external_libs/fast_double_parser/LICENSE.BSL'
warning: no files found matching '*' under directory 'compile/external_libs/fast_double_parser/include'
warning: no files found matching 'compile/external_libs/fmt/CMakeLists.txt'
warning: no files found matching 'compile/external_libs/fmt/LICENSE.rst'
warning: no files found matching '*' under directory 'compile/external_libs/fmt/include'
warning: no files found matching '*' under directory 'compile/include'
warning: no files found matching '*' under directory 'compile/src'
warning: no files found matching 'LightGBM.sln' under directory 'compile/windows'
warning: no files found matching 'LightGBM.vcxproj' under directory 'compile/windows'
warning: no files found matching '*.dll' under directory 'compile/windows/x64/DLL'
warning: no previously-included files matching '*.py[co]' found anywhere in distribution
warning: no previously-included files found matching 'compile/external_libs/compute/.git'
writing manifest file 'lightgbm.egg-info/SOURCES.txt'
copying lightgbm/VERSION.txt -> build/lib/lightgbm
running install_lib
INFO:LightGBM:Installing lib_lightgbm from: ['/content/LightGBM/lib_lightgbm.so']
running install_egg_info
removing '/usr/lib/python3.7/site-packages/lightgbm-3.3.1.99-py3.7.egg-info' (and everything under it)
Copying lightgbm.egg-info to /usr/lib/python3.7/site-packages/lightgbm-3.3.1.99-py3.7.egg-info
running install_scripts

In [100]:
!pip uninstall numpy
!pip uninstall pandas

!pip install --user numpy
!pip install --user  pandas

Found existing installation: numpy 1.21.5
Uninstalling numpy-1.21.5:
  Would remove:
    /usr/local/bin/f2py
    /usr/local/bin/f2py3
    /usr/local/bin/f2py3.7
    /usr/local/lib/python3.7/dist-packages/numpy-1.21.5.dist-info/*
    /usr/local/lib/python3.7/dist-packages/numpy.libs/libgfortran-2e0d59d6.so.5.0.0
    /usr/local/lib/python3.7/dist-packages/numpy.libs/libopenblasp-r0-2d23e62b.3.17.so
    /usr/local/lib/python3.7/dist-packages/numpy.libs/libquadmath-2d0c479f.so.0.0.0
    /usr/local/lib/python3.7/dist-packages/numpy/*
Proceed (y/n)? y
  Successfully uninstalled numpy-1.21.5
Found existing installation: pandas 1.3.5
Uninstalling pandas-1.3.5:
  Would remove:
    /root/.local/lib/python3.7/site-packages/pandas-1.3.5.dist-info/*
    /root/.local/lib/python3.7/site-packages/pandas/*
Proceed (y/n)? y
  Successfully uninstalled pandas-1.3.5
Collecting numpy
  Using cached numpy-1.21.5-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (15.7 MB)
Installing collected packages: numpy
  WARNING: The scripts f2py, f2py3 and f2py3.7 are installed in '/root/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
xarray 0.18.2 requires pandas>=1.0, which is not installed.
statsmodels 0.10.2 requires pandas>=0.19, which is not installed.
sklearn-pandas 1.8.0 requires pandas>=0.11.0, which is not installed.
seaborn 0.11.2 requires pandas>=0.23, which is not installed.
pymc3 3.11.4 requires pandas>=0.24.0, which is not installed.
plotnine 0.6.0 requires pandas>=0.25.0, which is not installed.
mlxtend 0.14.0 requires pandas>=0.17.1, which is not installed.
mizani 0.6.0 requires pandas>=0.25.0, which is not installed.
holoviews 1.14.6 requires pandas>=0.20.0, which is not installed.
fix-yahoo-finance 0.0.22 requires pandas, which is not installed.
fbprophet 0.7.1 requires pandas>=1.0.4, which is not installed.
fastai 1.0.61 requires pandas, which is not installed.
cufflinks 0.17.3 requires pandas>=0.19.2, which is not installed.
cmdstanpy 0.9.5 requires pandas, which is not installed.
arviz 0.11.4 requires pandas>=0.23, which is not installed.
altair 4.1.0 requires pandas>=0.18, which is not installed.
yellowbrick 1.3.post1 requires numpy<1.20,>=1.16.0, but you have numpy 1.21.5 which is incompatible.
datascience 0.10.6 requires folium==0.2.1, but you have folium 0.8.3 which is incompatible.
albumentations 0.1.12 requires imgaug<0.2.7,>=0.2.5, but you have imgaug 0.2.9 which is incompatible.
Successfully installed numpy-1.21.5

Collecting pandas
  Using cached pandas-1.3.5-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.3 MB)
Requirement already satisfied: numpy>=1.17.3 in /root/.local/lib/python3.7/site-packages (from pandas) (1.21.5)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (2018.9)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas) (1.15.0)
Installing collected packages: pandas
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires pandas~=1.1.0; python_version >= "3.0", but you have pandas 1.3.5 which is incompatible.
Successfully installed pandas-1.3.5

In [15]:
import matplotlib.pyplot as plt
plt.rc('font', family='NanumBarunGothic') 
import tensorflow as tf
import keras
from numpy import array
import pandas as pd
from google.colab import drive
import matplotlib.pyplot as plt
import numpy as np
import math
import matplotlib as mpl
from IPython.core.display import display, HTML
from datetime import datetime
from datetime import timedelta
from dateutil.relativedelta import relativedelta
from sklearn.preprocessing import MinMaxScaler, RobustScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error, f1_score
from tensorflow.keras import Sequential
from tensorflow.keras import layers
from tensorflow.keras.layers import Dense, LSTM, Dropout
from keras.callbacks import ModelCheckpoint, EarlyStopping
import urllib.request
import json
import datetime
import os
from datetime import datetime
from tqdm import tqdm
import warnings
from glob import glob
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder
from lightgbm import LGBMClassifier

In [2]:
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).

In [3]:
warnings.filterwarnings(action='ignore') 
know_train = [pd.read_csv(path) for path in sorted(glob('/content/gdrive/MyDrive/data/know/train/*.csv'))]

In [130]:
know2017 = pd.read_csv('/content/gdrive/MyDrive/data/know/전처리/know2017.csv')

## 모델

In [131]:
know2017 = know2017.iloc[:,2:]
know2017.head(2)

   aq1_1 aq1_2  aq2_1  ... knowcode                label_tool label_major
0      3     3      3  ...   825101                   [22613]         [0]
1      4     5      4  ...   140204  [1, 22492, 22611, 22553]         [1]

[2 rows x 157 columns]

In [132]:
# 전처리한 칼럼 삭제
know2017 = know2017.drop(columns=['bq31','bq38_1'])

In [133]:
know2017.head(3)

   aq1_1 aq1_2  aq2_1  ... knowcode                label_tool label_major
0      3     3      3  ...   825101                   [22613]         [0]
1      4     5      4  ...   140204  [1, 22492, 22611, 22553]         [1]
2      3     4      3  ...   140204  [5, 21376, 18390, 16369]         [1]

[3 rows x 155 columns]

### tool 리스트로

In [140]:
def remove_galho(text:str):
  return text[1:-1]

know2017['label_tool'] = know2017['label_tool'].map(remove_galho)

In [141]:
def text_to_list(text:str):
  result = []
  for i in text.split(','):
    result.append(int(i))
  return result

know2017['label_tool'] = know2017['label_tool'].map(text_to_list)

In [147]:
know2017['label_tool']

[0]

In [137]:
know2017['label_tool']

0                               [22613]
1              [1, 22492, 22611, 22553]
2              [5, 21376, 18390, 16369]
3                               [9, 10]
4                    [22530, 22605, 13]
                     ...
9481       [22646, 22647, 22648, 22649]
9482    [22650, 22651, 22652, 22653, 0]
9483                     [22654, 22655]
9484                            [22656]
9485                            [22657]
Name: label_tool, Length: 9486, dtype: object

In [138]:

def list_truncate(tool:list):
  if len(tool) > 3:
    return tool[:3]
  elif len(tool) == 3:
    return tool
  elif len(tool) == 2:
    return tool+['0']
  elif len(tool) == 1:
    return tool+['0', '0']
  elif len(tool) == 0:
    return ['0', '0', '0']

know2017['label_tool'] = know2017['label_tool'].map(list_truncate)

def list_to_feature1(tool:list):
  return tool[0]

def list_to_feature2(tool:list):
  return tool[1]

def list_to_feature3(tool:list):
  return tool[2]


feature1 = know2017['label_tool'].map(list_to_feature1)
feature2 = know2017['label_tool'].map(list_to_feature2)
feature3 = know2017['label_tool'].map(list_to_feature3)

know2017['feature1'] = feature1
know2017['feature2'] = feature2
know2017['feature3'] = feature3

know2017[['feature1', 'feature2', 'feature3']]

      feature1 feature2 feature3
0        22613        0        0
1            1    22492    22611
2            5    21376    18390
3            9       10        0
4        22530    22605       13
...        ...      ...      ...
9481     22646    22647    22648
9482     22650    22651    22652
9483     22654    22655        0
9484     22656        0        0
9485     22657        0        0

[9486 rows x 3 columns]

### 전공 리스트로

In [ ]:
def remove_galho(text:str):
  return text[1:-1]

know2017['label_major'] = know2017['label_major'].map(remove_galho)

In [ ]:
def text_to_list(text:str):
  result = []
  for i in text.split(','):
    result.append(int(i))
  return result

know2017['label_major'] = know2017['label_major'].map(text_to_list)

In [148]:

def list_truncate(tool:list):
  if len(tool) > 3:
    return tool[:3]
  elif len(tool) == 3:
    return tool
  elif len(tool) == 2:
    return tool+['0']
  elif len(tool) == 1:
    return tool+['0', '0']
  elif len(tool) == 0:
    return ['0', '0', '0']

know2017['label_tool'] = know2017['label_tool'].map(list_truncate)
def list_to_feature1(tool:list):
  return tool[0]

major1 = know2017['label_major'].map(list_to_feature1)

know2017['major'] = major1

In [150]:
know2017.head(3)

   aq1_1 aq1_2  aq2_1 aq2_2  ...  feature1 feature2  feature3 major
0      3     3      3     3  ...     22613        0         0     0
1      4     5      4     5  ...         1    22492     22611     1
2      3     4      3     4  ...         5    21376     18390     1

[3 rows x 159 columns]

In [152]:
# 전처리한 칼럼 삭제
know2017 = know2017.drop(columns=['label_tool','label_major'])

In [153]:
know2017.head(3)

   aq1_1 aq1_2  aq2_1 aq2_2  aq3_1  ... knowcode  feature1 feature2  feature3 major
0      3     3      3     3      3  ...   825101     22613        0         0     0
1      4     5      4     5      3  ...   140204         1    22492     22611     1
2      3     4      3     4      3  ...   140204         5    21376     18390     1

[3 rows x 157 columns]

In [213]:
know2017.iloc[:,86]

0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
       ...
9481    NaN
9482    NaN
9483    NaN
9484    NaN
9485    NaN
Name: bq4_1c, Length: 9486, dtype: object

In [212]:
np.where(know2017 == '산업안전산업기사이상')

(array([15]), array([86]))

In [202]:
# 현지가 전처리 안한 칼럼 삭제하고 모델링
know2017 = know2017.drop(columns=['bq4_1a','bq5_2','bq4_1b'])

KeyError: ignored

In [209]:
know2017 = know2017.drop(columns=['bq4_1b'])

KeyError: ignored

In [214]:
know2017 = know2017.drop(columns=['bq4_1c'])

In [220]:
know2017 = know2017.drop(columns=['bq19_1'])

KeyError: ignored

In [154]:
cat_features = ['bq30',	'bq32',	'bq33',	'bq34', 'feature1', 'feature2', 'feature3','major']

know2017[cat_features] = know2017[cat_features].astype('category')

In [215]:
col = ['aq1_2', 'aq2_2', 'aq3_2', 'aq4_2', 'aq5_2', 'aq6_2', 'aq7_2', 'aq8_2', 'aq9_2', 'aq10_2', 'aq11_2', 'aq12_2', 'aq13_2', 'aq14_2', 'aq15_2', 'aq16_2', 'aq17_2', 'aq18_2', 'aq19_2', 'aq20_2', 'aq21_2', 'aq22_2', 'aq23_2', 'aq24_2', 'aq25_2', 'aq26_2', 'aq27_2', 'aq28_2', 'aq29_2', 'aq30_2', 'aq31_2', 'aq32_2', 'aq33_2', 'aq34_2', 'aq35_2', 'aq36_2', 'aq37_2', 'aq38_2', 'aq39_2', 'aq40_2', 'aq41_2', 'bq5_1', 'bq12_2', 'bq12_3', 'bq12_4', 'bq40', 'bq41_1', 'bq41_2', 'bq41_3']

know2017[col] = know2017[col].replace(" ",np.nan)
know2017[col] = know2017[col].astype(float)

In [221]:
X_2017 = know2017.drop(columns=['knowcode'])
y_2017 = know2017['knowcode']


X_train_2017,X_test_2017,y_train_2017,y_test_2017 = train_test_split(X_2017,y_2017,test_size=0.2,random_state=10)

In [222]:
model = LGBMClassifier()
model.fit(X_train_2017, y_train_2017)

LGBMClassifier()

In [223]:
pred = model.predict(X_test_2017)

In [229]:
pred

array([ 24301, 414102, 155305, ..., 155305, 155305, 621201])

In [227]:
y_test_2017.values

array([531601, 872101, 307501, ..., 817201, 842301, 885201])

In [230]:
accuracy_score(y_test_2017.values, pred)

0.05795574288724974